services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_init:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/db
    command: python -m project.db_init

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/db
    volumes:
    - ./logs:/app/logs
    command: python -m project.main

  db_test:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"

  test:
    build: .
    depends_on:
      - db_test
    environment:
      DATABASE_URL: postgresql://user:password@db_test:5433/test_db
    command: pytest -v

volumes:
  postgres_data:
